vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        articles:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            # le fichier doit-il être injecté dans l'entité téléchargeable lorsqu'il est chargé depuis le magasin de données. L'objet sera une instance de Symfony\Component\HttpFoundation\File\File.
            inject_on_load: false
            #le fichier doit-il être supprimé lorsqu'un nouveau fichier est téléchargé ;
            delete_on_update: true
            # le fichier doit-il être supprimé lorsque l'entité est supprimée ;
            delete_on_remove: true

        category:
            uri_prefix: /images/category
            upload_destination: '%kernel.project_dir%/public/images/category'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            # le fichier doit-il être injecté dans l'entité téléchargeable lorsqu'il est chargé depuis le magasin de données. L'objet sera une instance de Symfony\Component\HttpFoundation\File\File.
            inject_on_load: false
            #le fichier doit-il être supprimé lorsqu'un nouveau fichier est téléchargé ;
            delete_on_update: true
            # le fichier doit-il être supprimé lorsque l'entité est supprimée ;
            delete_on_remove: true

        searchnotices:
            uri_prefix: /images/searchnotices
            upload_destination: '%kernel.project_dir%/public/images/searchnotices'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            # le fichier doit-il être injecté dans l'entité téléchargeable lorsqu'il est chargé depuis le magasin de données. L'objet sera une instance de Symfony\Component\HttpFoundation\File\File.
            inject_on_load: false
            #le fichier doit-il être supprimé lorsqu'un nouveau fichier est téléchargé ;
            delete_on_update: true
            # le fichier doit-il être supprimé lorsque l'entité est supprimée ;
            delete_on_remove: true